services:
  worbes-api:
    container_name: worbes-api-local
    image: worbes-api:local
    ports:
      - "8080:8080"
      - "9292:9292"
    env_file: .env.local
    depends_on:
      - worbes-db

  worbes-batch:
    container_name: worbes-batch-local
    image: worbes-batch:local
    ports:
      - "8080:8080"
      - "9292:9292"
    env_file: .env.local
    depends_on:
      - worbes-db

  worbes-db:
    container_name: worbes-db-local
    image: postgres:17.3
    env_file: .env.local
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:latest
    container_name: worbes-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"