-- ================================
-- V1__init_schema.sql
-- ================================

-- auction 테이블
create table if not exists public.auction
(
    auction_id bigint      not null
        unique,
    created_at timestamptz,
    ended_at   timestamptz,
    id         bigint generated by default as identity
        primary key,
    item_id    bigint      not null,
    price      integer     not null CHECK (price >= 1),
    quantity   bigint      not null CHECK (quantity >= 0),
    realm_id   bigint,
    region     varchar(10) not null
        constraint auction_region_check
            check ((region)::text = ANY ((ARRAY ['US'::character varying, 'KR'::character varying])::text[]))
);

alter table public.auction
    owner to "worbes-admin";

-- item 테이블
create table if not exists public.item
(
    crafting_tier    smallint
        constraint item_crafting_tier_check
            check ((crafting_tier >= 0) AND (crafting_tier <= 4)),
    level            integer      not null,
    created_at       timestamp(6),
    id               bigint       not null
        primary key,
    item_class_id    bigint       not null,
    item_subclass_id bigint       not null,
    updated_at       timestamp(6),
    inventory_type   varchar(20)  not null
        constraint item_inventory_type_check
            check ((inventory_type)::text = ANY
                   ((ARRAY ['NON_EQUIP'::character varying, 'HEAD'::character varying, 'NECK'::character varying, 'SHOULDER'::character varying, 'BODY'::character varying, 'CHEST'::character varying, 'WAIST'::character varying, 'LEGS'::character varying, 'FEET'::character varying, 'WRIST'::character varying, 'HAND'::character varying, 'FINGER'::character varying, 'TRINKET'::character varying, 'WEAPON'::character varying, 'SHIELD'::character varying, 'RANGED'::character varying, 'CLOAK'::character varying, 'TWOHWEAPON'::character varying, 'BAG'::character varying, 'TABARD'::character varying, 'ROBE'::character varying, 'WEAPONMAINHAND'::character varying, 'WEAPONOFFHAND'::character varying, 'HOLDABLE'::character varying, 'AMMO'::character varying, 'THROWN'::character varying, 'RANGEDRIGHT'::character varying, 'QUIVER'::character varying, 'RELIC'::character varying, 'PROFESSION_TOOL'::character varying, 'PROFESSION_GEAR'::character varying, 'EQUIPABLESPELL_OFFENSIVE'::character varying, 'EQUIPABLESPELL_UTILITY'::character varying, 'EQUIPABLESPELL_DEFENSIVE'::character varying, 'EQUIPABLESPELL_WEAPON'::character varying])::text[])),
    quality          varchar(20)  not null
        constraint item_quality_check
            check ((quality)::text = ANY
                   ((ARRAY ['POOR'::character varying, 'COMMON'::character varying, 'UNCOMMON'::character varying, 'RARE'::character varying, 'EPIC'::character varying, 'LEGENDARY'::character varying, 'ARTIFACT'::character varying, 'HEIRLOOM'::character varying, 'WOW_TOKEN'::character varying])::text[])),
    icon_url         varchar(255) not null,
    name             jsonb        not null,
    preview_item     jsonb        not null
);

alter table public.item
    owner to "worbes-admin";

-- realm 테이블
create table if not exists public.realm
(
    connected_realm_id bigint      not null,
    created_at         timestamp(6),
    id                 bigint      not null
        primary key,
    updated_at         timestamp(6),
    region             varchar(10) not null
        constraint realm_region_check
            check ((region)::text = ANY ((ARRAY ['US'::character varying, 'KR'::character varying])::text[])),
    slug               varchar(50) not null,
    name               jsonb       not null,
    constraint uq_region_slug
        unique (region, slug)
);

alter table public.realm
    owner to "worbes-admin";

---
CREATE OR REPLACE VIEW auction_hourly_snapshot_view AS
WITH hours AS (SELECT DISTINCT DATE_TRUNC('hour', created_at) AS hour,
                               item_id,
                               region,
                               realm_id
               FROM auction),
     summary AS (SELECT h.hour                                                                  AS time,
                        h.item_id,
                        h.region,
                        h.realm_id,
                        (SELECT SUM(a.quantity)
                         FROM auction a
                         WHERE a.item_id = h.item_id
                           AND a.region = h.region
                           AND a.realm_id IS NOT DISTINCT FROM h.realm_id
                           AND DATE_TRUNC('hour', a.created_at) <= h.hour
                           AND (a.ended_at IS NULL OR DATE_TRUNC('hour', a.ended_at) > h.hour)) AS total_quantity,
                        (SELECT MIN(a.price)
                         FROM auction a
                         WHERE a.item_id = h.item_id
                           AND a.region = h.region
                           AND a.realm_id IS NOT DISTINCT FROM h.realm_id
                           AND DATE_TRUNC('hour', a.created_at) <= h.hour
                           AND (a.ended_at IS NULL OR DATE_TRUNC('hour', a.ended_at) > h.hour)) AS min_price
                 FROM hours h)
SELECT *
FROM summary
ORDER BY time;
