-- ============================
-- 테스트용 realm 데이터 삽입
-- ============================

INSERT INTO realm (id, region, connected_realm_id, name, slug, created_at, updated_at)
VALUES (258, 'KR', 214, '{
  "de_DE": "Alexstrasza",
  "en_GB": "Alexstrasza",
  "en_US": "Alexstrasza",
  "es_ES": "Alexstrasza",
  "es_MX": "Alexstrasza",
  "fr_FR": "Alexstrasza",
  "it_IT": "Alexstrasza",
  "ko_KR": "알렉스트라자",
  "pt_BR": "Alexstrasza",
  "ru_RU": "Alexstrasza",
  "zh_CN": "红龙女王",
  "zh_TW": "雅立史卓莎"
}', 'alexstrasza', now(), now()),
       (2116, 'KR', 2116, '{
         "de_DE": "Zul''jin",
         "en_GB": "Zul''jin",
         "en_US": "Zul''jin",
         "es_ES": "Zul''jin",
         "es_MX": "Zul''jin",
         "fr_FR": "Zul''jin",
         "it_IT": "Zul''jin",
         "ko_KR": "줄진",
         "pt_BR": "Zul''jin",
         "ru_RU": "Zul''jin",
         "zh_CN": "祖尔金",
         "zh_TW": "祖爾金"
       }', 'zuljin', now(), now()),
       (293, 'KR', 2116, '{
         "de_DE": "Hellscream",
         "en_GB": "Hellscream",
         "en_US": "Hellscream",
         "es_ES": "Hellscream",
         "es_MX": "Hellscream",
         "fr_FR": "Hellscream",
         "it_IT": "Hellscream",
         "ko_KR": "헬스크림",
         "pt_BR": "Hellscream",
         "ru_RU": "Hellscream",
         "zh_CN": "地狱咆哮",
         "zh_TW": "地獄吼"
       }', 'hellscream', now(), now()),
       (264, 'KR', 2116, '{
         "de_DE": "Malfurion",
         "en_GB": "Malfurion",
         "en_US": "Malfurion",
         "es_ES": "Malfurion",
         "es_MX": "Malfurion",
         "fr_FR": "Malfurion",
         "it_IT": "Malfurion",
         "ko_KR": "말퓨리온",
         "pt_BR": "Malfurion",
         "ru_RU": "Malfurion",
         "zh_CN": "玛法里奥",
         "zh_TW": "瑪法里恩"
       }', 'malfurion', now(), now()),
       (201, 'KR', 210, '{
         "de_DE": "Burning Legion",
         "en_GB": "Burning Legion",
         "en_US": "Burning Legion",
         "es_ES": "Burning Legion",
         "es_MX": "Burning Legion",
         "fr_FR": "Burning Legion",
         "it_IT": "Burning Legion",
         "ko_KR": "불타는 군단",
         "pt_BR": "Burning Legion",
         "ru_RU": "Burning Legion",
         "zh_CN": "燃烧军团",
         "zh_TW": "燃燒軍團"
       }', 'burning-legion', now(), now()),
       (205, 'KR', 205, '{
         "de_DE": "Azshara",
         "en_GB": "Azshara",
         "en_US": "Azshara",
         "es_ES": "Azshara",
         "es_MX": "Azshara",
         "fr_FR": "Azshara",
         "it_IT": "Azshara",
         "ko_KR": "아즈샤라",
         "pt_BR": "Azshara",
         "ru_RU": "Azshara",
         "zh_CN": "艾萨拉",
         "zh_TW": "艾薩拉"
       }', 'azshara', now(), now()),
       (207, 'KR', 2116, '{
         "de_DE": "Dalaran",
         "en_GB": "Dalaran",
         "en_US": "Dalaran",
         "es_ES": "Dalaran",
         "es_MX": "Dalaran",
         "fr_FR": "Dalaran",
         "it_IT": "Dalaran",
         "ko_KR": "달라란",
         "pt_BR": "Dalaran",
         "ru_RU": "Dalaran",
         "zh_CN": "达拉然",
         "zh_TW": "達拉然"
       }', 'dalaran', now(), now()),
       (210, 'KR', 210, '{
         "de_DE": "Durotan",
         "en_GB": "Durotan",
         "en_US": "Durotan",
         "es_ES": "Durotan",
         "es_MX": "Durotan",
         "fr_FR": "Durotan",
         "it_IT": "Durotan",
         "ko_KR": "듀로탄",
         "pt_BR": "Durotan",
         "ru_RU": "Durotan",
         "zh_CN": "杜隆坦",
         "zh_TW": "杜洛坦"
       }', 'durotan', now(), now()),
       (211, 'KR', 2116, '{
         "de_DE": "Norgannon",
         "en_GB": "Norgannon",
         "en_US": "Norgannon",
         "es_ES": "Norgannon",
         "es_MX": "Norgannon",
         "fr_FR": "Norgannon",
         "it_IT": "Norgannon",
         "ko_KR": "노르간논",
         "pt_BR": "Norgannon",
         "ru_RU": "Norgannon",
         "zh_CN": "诺甘农",
         "zh_TW": "諾甘農"
       }', 'norgannon', now(), now()),
       (212, 'KR', 2116, '{
         "de_DE": "Garona",
         "en_GB": "Garona",
         "en_US": "Garona",
         "es_ES": "Garona",
         "es_MX": "Garona",
         "fr_FR": "Garona",
         "it_IT": "Garona",
         "ko_KR": "가로나",
         "pt_BR": "Garona",
         "ru_RU": "Garona",
         "zh_CN": "迦罗娜",
         "zh_TW": "迦羅娜"
       }', 'garona', now(), now()),
       (214, 'KR', 214, '{
         "de_DE": "Windrunner",
         "en_GB": "Windrunner",
         "en_US": "Windrunner",
         "es_ES": "Windrunner",
         "es_MX": "Windrunner",
         "fr_FR": "Windrunner",
         "it_IT": "Windrunner",
         "ko_KR": "윈드러너",
         "pt_BR": "Windrunner",
         "ru_RU": "Ветрокрылая",
         "zh_CN": "风行者",
         "zh_TW": "風行者"
       }', 'windrunner', now(), now()),
       (215, 'KR', 2116, '{
         "de_DE": "Gul''dan",
         "en_GB": "Gul''dan",
         "en_US": "Gul''dan",
         "es_ES": "Gul''dan",
         "es_MX": "Gul''dan",
         "fr_FR": "Gul''dan",
         "it_IT": "Gul''dan",
         "ko_KR": "굴단",
         "pt_BR": "Gul''dan",
         "ru_RU": "Gul''dan",
         "zh_CN": "古尔丹",
         "zh_TW": "古爾丹"
       }', 'guldan', now(), now()),
       (2106, 'KR', 214, '{
         "de_DE": "Rexxar",
         "en_GB": "Rexxar",
         "en_US": "Rexxar",
         "es_ES": "Rexxar",
         "es_MX": "Rexxar",
         "fr_FR": "Rexxar",
         "it_IT": "Rexxar",
         "ko_KR": "렉사르",
         "pt_BR": "Rexxar",
         "ru_RU": "Rexxar",
         "zh_CN": "雷克萨",
         "zh_TW": "雷克薩"
       }', 'rexxar', now(), now()),
       (2107, 'KR', 2116, '{
         "de_DE": "Hyjal",
         "en_GB": "Hyjal",
         "en_US": "Hyjal",
         "es_ES": "Hyjal",
         "es_MX": "Hyjal",
         "fr_FR": "Hyjal",
         "it_IT": "Hyjal",
         "ko_KR": "하이잘",
         "pt_BR": "Hyjal",
         "ru_RU": "Hyjal",
         "zh_CN": "海加尔",
         "zh_TW": "海加爾山"
       }', 'hyjal', now(), now()),
       (2108, 'KR', 214, '{
         "de_DE": "Deathwing",
         "en_GB": "Deathwing",
         "en_US": "Deathwing",
         "es_ES": "Deathwing",
         "es_MX": "Deathwing",
         "fr_FR": "Deathwing",
         "it_IT": "Deathwing",
         "ko_KR": "데스윙",
         "pt_BR": "Deathwing",
         "ru_RU": "Deathwing",
         "zh_CN": "死亡之翼",
         "zh_TW": "死亡之翼"
       }', 'deathwing', now(), now());
