-- ================================
-- V1_1__business_schema.sql
-- 비즈니스 도메인 테이블
-- ================================

-- ----------------------------------------------------------------------------
-- 1. Auction 도메인
-- ----------------------------------------------------------------------------

-- auction 테이블
CREATE TABLE IF NOT EXISTS public.auction
(
    id         bigint      NOT NULL PRIMARY KEY,
    item_id    bigint      NOT NULL,
    item_bonus jsonb,
    price      bigint      NOT NULL CHECK (price >= 100),
    quantity   integer     NOT NULL CHECK (quantity >= 1),
    region     varchar(10) NOT NULL
        CONSTRAINT auction_region_check
            CHECK ((region)::text = ANY ((ARRAY ['US'::character varying, 'KR'::character varying])::text[])),
    realm_id   bigint,
    created_at timestamptz(0)
);

CREATE INDEX IF NOT EXISTS idx_auction_item_realm_region
    ON auction (item_id, realm_id, region);

-- auction_snapshot 테이블
CREATE TABLE IF NOT EXISTS auction_snapshot
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id        bigint         NOT NULL,
    time           timestamptz(0) NOT NULL,
    realm_id       bigint,
    region         varchar(255)   NOT NULL,
    lowest_price   bigint         NOT NULL,
    total_quantity integer        NOT NULL,
    item_bonus     jsonb
    -- CONSTRAINT fk_auction_snapshot_item_id
    --     FOREIGN KEY (item_id) REFERENCES item (id)
);

---MAX(time) 쿼리 용 인덱스
CREATE INDEX IF NOT EXISTS idx_auction_snapshot_time
    ON auction_snapshot (time DESC);

---메인 쿼리 용 인덱스
CREATE INDEX IF NOT EXISTS idx_auction_snapshot_item_time_realm
    on auction_snapshot (item_id, time desc, realm_id);

-- ----------------------------------------------------------------------------
-- 2. Item 도메인
-- ----------------------------------------------------------------------------

-- item 테이블
CREATE TABLE IF NOT EXISTS public.item
(
    id             bigint       NOT NULL PRIMARY KEY,
    name           jsonb        NOT NULL,
    level          integer      NOT NULL,
    class_id       bigint       NOT NULL,
    subclass_id    bigint       NOT NULL,
    inventory_type varchar(20)  NOT NULL
        CONSTRAINT item_inventory_type_check
            CHECK ((inventory_type)::text = ANY
                   ((ARRAY ['NON_EQUIP'::character varying, 'HEAD'::character varying, 'NECK'::character varying, 'SHOULDER'::character varying, 'BODY'::character varying, 'CHEST'::character varying, 'WAIST'::character varying, 'LEGS'::character varying, 'FEET'::character varying, 'WRIST'::character varying, 'HAND'::character varying, 'FINGER'::character varying, 'TRINKET'::character varying, 'WEAPON'::character varying, 'SHIELD'::character varying, 'RANGED'::character varying, 'CLOAK'::character varying, 'TWOHWEAPON'::character varying, 'BAG'::character varying, 'TABARD'::character varying, 'ROBE'::character varying, 'WEAPONMAINHAND'::character varying, 'WEAPONOFFHAND'::character varying, 'HOLDABLE'::character varying, 'AMMO'::character varying, 'THROWN'::character varying, 'RANGEDRIGHT'::character varying, 'QUIVER'::character varying, 'RELIC'::character varying, 'PROFESSION_TOOL'::character varying, 'PROFESSION_GEAR'::character varying, 'EQUIPABLESPELL_OFFENSIVE'::character varying, 'EQUIPABLESPELL_UTILITY'::character varying, 'EQUIPABLESPELL_DEFENSIVE'::character varying, 'EQUIPABLESPELL_WEAPON'::character varying])::text[])),
    quality        smallint
        CONSTRAINT item_quality_check
            CHECK ((quality >= 1) AND (quality <= 6)),
    icon           varchar(255) NOT NULL,
    display_id     bigint,
    crafting_tier  smallint
        CONSTRAINT item_crafting_tier_check
            CHECK ((crafting_tier >= 1) AND (crafting_tier <= 3)),
    is_stackable   boolean      NOT NULL,
    expansion_id   smallint     NOT NULL,
    created_at     timestamp(0),
    updated_at     timestamp(0)
);

CREATE INDEX IF NOT EXISTS idx_item_class_subclass
    ON item (class_id, subclass_id);

-- item_bonus 테이블
CREATE TABLE IF NOT EXISTS item_bonus
(
    id         bigint PRIMARY KEY,
    suffix     varchar(100),
    level      int,
    base_level int,
    created_at timestamp(0),
    updated_at timestamp(0)
);

-- ----------------------------------------------------------------------------
-- 3. Realm 도메인
-- ----------------------------------------------------------------------------

-- realm 테이블
CREATE TABLE IF NOT EXISTS public.realm
(
    id                 bigint      NOT NULL PRIMARY KEY,
    region             varchar(10) NOT NULL
        CONSTRAINT realm_region_check
            CHECK ((region)::text = ANY ((ARRAY ['US'::character varying, 'KR'::character varying])::text[])),
    connected_realm_id bigint      NOT NULL,
    name               jsonb       NOT NULL,
    slug               varchar(50) NOT NULL,
    created_at         timestamp(0),
    updated_at         timestamp(0),
    CONSTRAINT uq_region_slug
        UNIQUE (region, slug)
);
