spring:
  datasource:
    url: jdbc:mysql://localhost:33060/worbes
    username: tester
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # create, update, validate 등 필요에 맞게 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8 기준
        use_sql_comments: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

blizzard:
  api:
    token: ${BLIZZARD_API_TOKEN}
