spring:
  datasource:
    url: jdbc:mysql://localhost:33060/worbes
    username: tester
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # create, update, validate 등 필요에 맞게 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8 기준
    show-sql: true # SQL 쿼리 로깅

