spring:
  profiles:
    active: local
    group:
      local:
        - db
        - redis
        - blizzard
---
spring:
  config:
    activate:
      on-profile: db
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true # JPA/Hibernate가 실행하는 SQL 쿼리를 콘솔에 출력
    hibernate:
      ddl-auto: update # create, update, validate
    properties:
      hibernate:
        order_updates: true
        format_sql: true # 쿼리를 보기 좋게 정렬
        jdbc:
          batch_size: 1000
#        use_sql_comments: true # (선택) SQL에 주석 표시
#        generate_statistics: true #배치 적용 됐는지 확인할 수 있는 통계 제공 옵션

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
spring:
  config:
    activate:
      on-profile: redis
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 4
          max-wait: 5000ms
---
spring:
  config:
    activate:
      on-profile: blizzard
blizzard:
  api:
    token-url: https://oauth.battle.net/token
    id: ${BLIZZARD_CLIENT_ID}
    secret: ${BLIZZARD_CLIENT_SECRET}
  required-classes:
    0: [ 0, 1, 2, 3, 5, 7, 8, 9 ]  # 소비 용품 (보조 수집품, 전투 수집품 제거)
    1: [ 0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ]  # 영혼의 가방(1) 제거
    2: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13, 14, 15, 16, 17, 18, 19, 20 ]  # 곰 발톱(11), 표범 발톱(12) 제거
    3: [ 0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11 ]  # 보석 (정신력(4) 제거)
    4: [ 0, 1, 2, 3, 4, 5, 6 ]  # 방어구 (성서(7), 우상(8), 토템(9), 인장(10), 성물(11) 제거)
    7: [ 1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 16, 18, 19 ]  # 필터링 없음
    8: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ]  # 방어구 토큰 (전체 저장)
    9: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ]  # 제조법 (전체 저장)
    12: [ 0 ] # 퀘스트 (전체 저장)
    15: [ 0, 1, 3, 4, 5, 6 ] # 애완동물 친구(2) 제거
    16: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 ] # 문양 전체 저장
    17: [ 0 ] # 전투애완 동물
    18: [ 0 ] # 와우 토큰
    19: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 ] # 전문기술 장비 (고고학(13) 제거)
---
