spring:
  profiles:
    active: local
    group:
      local:
        - db
        - redis
        - blizzard
---
spring:
  config:
    activate:
      on-profile: db
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # create, update, validate
    properties:
      use_sql_comments: true
      format_sql: true
      hibernate:
        jdbc:
          batch_size: 1000
        order_updates: true
        generate_statistics: true #배치 적용 됐는지 확인할 수 있는 통계 제공 옵션
---
spring:
  config:
    activate:
      on-profile: redis
  data:
    redis:
      host: localhost
      port: 6379
---
spring:
  config:
    activate:
      on-profile: blizzard
blizzard:
  api:
    token-url: https://oauth.battle.net/token
    id: ${BLIZZARD_CLIENT_ID}
    secret: ${BLIZZARD_CLIENT_SECRET}
---
