name: Deploy Worbes Build

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build & push API Server
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: aprileaf/worbes-api:latest
          file: ./bootstrap/worbes-api/Dockerfile

      - name: Build & push Batch app
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: aprileaf/worbes-batch:latest
          file: ./bootstrap/worbes-batch/Dockerfile
