name: Deploy Worbes Post

on:
  workflow_run:
    workflows: [ "Deploy Worbes Build" ]
    types: [ completed ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Create .env file
        run: echo "${{ secrets.APP_ENV }}" > .env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up docker context over SSH authentication
        uses: amirmarmul/docker-context-ssh-action@v2.1.3
        with:
          ssh-host: ${{ secrets.HOST }}
          ssh-username: ${{ secrets.USERNAME }}
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
          ssh-port: ${{ secrets.PORT }}

      - name: Use Remote Context
        run: docker context use remote

      - name: Docker compose pull
        run: docker compose pull

      - name: Docker compose up
        run: docker compose up -d
