name: Deploy Worbes Post

on:
  workflow_run:
    workflows: [ "Deploy Worbes Build" ]
    types: [ completed ]
    branches:
      - main

jobs:
  deploy:
    environment: dev
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "${{ secrets.APP_ENV }}" > ${{ runner.temp }}/.env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check if remote docker context exists
        id: check-context
        run: |
          if docker context inspect remote >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up docker context over SSH authentication
        if: steps.check-context.outputs.exists == 'false'
        uses: amirmarmul/docker-context-ssh-action@v2.1.3
        with:
          ssh-host: ${{ secrets.HOST }}
          ssh-username: ${{ secrets.USERNAME }}
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
          ssh-port: ${{ secrets.PORT }}

      - name: Use Remote Context
        run: docker context use remote

      - name: Docker compose pull
        run: docker compose pull

      - name: Docker compose up
        run: docker compose --env-file ${{ runner.temp }}/.env up -d

      - name: Clean up runner workspace
        if: always()
        run: |
          cd $GITHUB_WORKSPACE/..
          rm -rf $GITHUB_WORKSPACE
