name: Deploy Batch (Dev)

on:
  push:
    branches:
      - dev
    paths:
      - 'application/**'
      - 'adapter/persistence/**'
      - 'adapter/batch/**'
      - 'adapter/client-blizzard/**'
      - 'bootstrap/worbes-batch/**'
      - 'build.gradle'
      - 'settings.gradle'
jobs:
  deploy-batch:
    runs-on: ubuntu-latest
    steps:
      # 빌드 & 푸시
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: aprileaf/worbes-batch:dev
          file: ./bootstrap/worbes-batch/Dockerfile
          cache-from: type=registry,ref=aprileaf/worbes-batch:buildcache
          cache-to: type=registry,ref=aprileaf/worbes-batch:buildcache,mode=max

  deploy:
    needs: deploy-batch
    if: success()
    environment: dev
    runs-on: [ self-hosted, batch-server ]
    steps:
      - name: Checkout compose.dev.yml
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            compose.dev.yml
          sparse-checkout-cone-mode: false

      - name: Create .env
        run: echo "${{ secrets.ENV }}" > .env.dev

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker compose pull
        run: docker compose -f compose.dev.yml pull worbes-batch

      - name: Docker compose up
        run: docker compose -f compose.dev.yml up -d worbes-batch

      - name: Remove unused Docker images
        run: docker image prune -af

      - name: Clean up runner workspace
        if: always()
        run: |
          shopt -s dotglob
          rm -rf $GITHUB_WORKSPACE/*
