name: Integration Test

on:
  pull_request:
    branches: [ dev, main ]
jobs:
  Integration:
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref }}
    services:
      postgres:
        image: postgres:17.3
        env:
          POSTGRES_PASSWORD: 1234
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6543:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # PostgreSQL 연결 테스트 추가
      - name: Test PostgreSQL connection
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          PGPASSWORD=1234 psql -h localhost -p 6543 -U postgres -c "SELECT version();"

      # 환경변수 출력 (디버깅용)
      - name: Print environment info
        run: |
          echo "Java version:"
          java -version
          echo "Environment variables:"
          env | grep -E "(POSTGRES|DATABASE|SPRING)" || true

      - name: Run tests with detailed logging
        run: |
          ./gradlew clean test \
            --info \
            --stacktrace \
            --debug \
            -Dlogging.level.org.springframework=DEBUG \
            -Dlogging.level.org.flywaydb=DEBUG \
            -Dlogging.level.org.postgresql=DEBUG \
            -Dspring.jpa.show-sql=true \
            -Dspring.jpa.properties.hibernate.format_sql=true
