name: Integration Test

on:
  pull_request:
    branches: [ dev, main ]
jobs:
  Integration:
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref }}
    services:
      postgres:
        image: postgres:17.3
        env:
          POSTGRES_PASSWORD: 1234
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6543:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew clean test
